baseURL = 'https://boot.dev/'
languageCode = 'en-us'
title = 'Boot.dev Blog'
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = []
footnotereturnlinkcontents = "↩"

[taxonomies]
  category = "categories"

[permalinks]
post = "/:section/:slug/"

[params]
description = "We teach computer science through hands-on coding projects. We’re built for developers who want to advance their careers."
footer = "&copy; [Boot.dev](https://boot.dev) {Year}"

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true
